import {StyleSheet, Dimensions} from 'react-native';
import {Colors, Fonts} from 'styles';
import {RFValue, RFPercentage} from 'react-native-responsive-fontsize';
const {width} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: width * 0.04,
  },
  titleInput: {
    fontSize: RFValue(18),
    fontFamily: Fonts.ARIAL_ROUNDED_BOLD,
    marginVertical: width * 0.03,
    color: Colors.BLACK,
  },
  imageSection: {
    flexDirection: 'row',
  },
  imagePostItem: {
    flex: 1,
    marginRight: width * 0.03,
  },
  imagePost: {
    width: '100%',
    height: width * 0.5,
    borderRadius: 10,
  },
  imageButtonClose: {
    width: width * 0.07,
    height: width * 0.07,
    backgroundColor: Colors.WHITE_MEDIUM,
    borderRadius: 75,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: width * 0.02,
    top: width * 0.02,
  },
  imageButtonCloseIcon: {
    fontSize: RFValue(16),
    color: Colors.PRIMARY_DARK,
  },
  bodyInput: {
    fontSize: RFValue(14),
    height: width * 0.8,
    maxHeight: width * 0.8,
    textAlignVertical: 'top',
    fontFamily: Fonts.ARIAL_ROUNDED_BOLD,
    color: Colors.BLACK,
  },
  optionSection: {
    width: width,
    backgroundColor: Colors.WHITE,
    borderTopLeftRadius: width * 0.05,
    borderTopRightRadius: width * 0.05,
    elevation: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    paddingHorizontal: width * 0.04,
    paddingVertical: width * 0.02,
    flexDirection: 'row',
    alignItems: 'center',
  },
  optionBubbleSection: {
    width: width * 0.1,
    height: width * 0.1,
    backgroundColor: Colors.WHITE_MEDIUM,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 75,
    marginRight: width * 0.06,
  },
  optionIcon: {
    fontSize: RFValue(20),
    color: Colors.BLACK,
  },
  hdFAndroid: {
    height: width * 0.16,
    backgroundColor: Colors.WHITE,
    elevation: 2,
  },
  hdFAndroidSection: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: width * 0.04,
  },
  hdFAndroidLeft: {
    flex: 1,
  },
  hdFBubleRounded: {
    width: width * 0.1,
    height: width * 0.1,
    borderRadius: 75,
    backgroundColor: Colors.WHITE_MEDIUM,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hdFBubbleIcon: {
    fontSize: RFValue(22),
  },
  hdFAndroidWrap: {
    backgroundColor: Colors.GRAY_LIGHT100,
    paddingHorizontal: width * 0.04,
    paddingVertical: width * 0.015,
    borderRadius: 75,
  },
  hdFAndroidPost: enable => ({
    fontFamily: Fonts.ARIAL_ROUNDED_BOLD,
    fontSize: RFValue(14),
    color: enable ? Colors.GRAY_LIGHT200 : Colors.PRIMARY_DARK,
  }),

  linkSection: {
    height: width * 0.15,
    paddingHorizontal: width * 0.04,
    backgroundColor: Colors.WHITE,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  linkButtonCancel: {
    width: width * 0.1,
    height: width * 0.1,
    borderRadius: 75,
    backgroundColor: Colors.GRAY_LIGHT100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  linkButtonCancelTitle: {
    fontSize: RFValue(18),
    color: Colors.PRIMARY_DARK,
  },
  linkButtonSave: {
    paddingHorizontal: width * 0.05,
    height: width * 0.1,
    backgroundColor: Colors.PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 75,
  },
  linkButtonSaveTitle: {
    fontFamily: Fonts.ARIAL_ROUNDED_BOLD,
    fontSize: RFValue(14),
    color: Colors.WHITE,
  },
  linkInputSection: {
    flex: 1,
    height: width * 0.1,
    borderWidth: 1,
    borderColor: Colors.GRAY_LIGHT200,
    marginHorizontal: width * 0.02,
    borderRadius: 75,
  },
  linkInput: {
    paddingLeft: width * 0.04,
  },
  linkHref: {
    fontSize: RFValue(12),
    fontFamily: Fonts.ARIAL_ROUNDED_BOLD,
    marginTop: width * 0.04,
  },
  modalContainer: {
    margin: 0,
    padding: 0,
  },
  modalSection: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalContent: {
    height: width * 1.5,
    backgroundColor: Colors.WHITE,
    borderTopLeftRadius: width * 0.05,
    borderTopRightRadius: width * 0.05,
  },
  modalTitle: {
    fontFamily: Fonts.ARIAL_ROUNDED_BOLD,
    fontSize: RFValue(16),
    color: Colors.PRIMARY_DARK,
    textAlign: 'center',
    marginVertical: width * 0.04,
  },
  tpItemSection: {
    paddingHorizontal: width * 0.04,
    // marginVertical: width * 0.05,
  },
  tpItem: isSelected => ({
    flexDirection: 'row',
    alignItems: 'center',
    // marginVertical: width * 0.04,
    marginVertical: width * 0.01,
    borderWidth: isSelected ? 1 : 0,
    paddingHorizontal: width * 0.02,
    height: width * 0.2,
    borderRadius: width * 0.03,
    borderColor: Colors.PRIMARY,
  }),
  tpIcon: {
    width: width * 0.1,
    height: width * 0.1,
  },
  tpInfoSection: {
    flex: 1,
    paddingLeft: width * 0.04,
  },
  tpTitle: {
    fontSize: RFValue(16),
    fontFamily: Fonts.ARIAL_ROUNDED_BOLD,
  },
  tpSubTitle: {
    fontFamily: Fonts.ARIAL,
    color: Colors.BLACK_LABLE,
    fontSize: RFValue(12),
  },
  checlistButton: isSelected => ({
    width: width * 0.07,
    height: width * 0.07,
    marginLeft: width * 0.01,
    backgroundColor: isSelected ? Colors.PRIMARY : Colors.GRAY_LIGHT100,
    borderRadius: 75,
    alignItems: 'center',
    justifyContent: 'center',
  }),
  checlistButtonIcon: {
    fontSize: RFValue(18),
    color: Colors.WHITE,
  },
  closeModalButton: outline => ({
    marginHorizontal: width * 0.05,
    height: width * 0.11,
    backgroundColor: outline ? Colors.WHITE : Colors.PRIMARY,
    borderWidth: outline ? 1.5 : 0,
    borderColor: outline ? Colors.PRIMARY : Colors.WHITE,
    marginVertical: width * 0.02,
    marginBottom: outline ? width * 0.05 : 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: width * 0.047,
  }),
  closeModalButtonTitle: outline => ({
    fontSize: RFValue(14.5),
    fontFamily: Fonts.ARIAL_ROUNDED_BOLD,
    color: outline ? Colors.PRIMARY : Colors.WHITE,
  }),
  optionTopicSelected: {
    flex: 1,
    backgroundColor: Colors.GRAY_LIGHT100,
    paddingHorizontal: width * 0.04,
    paddingVertical: width * 0.02,
    borderRadius: 75,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: -width * 0.04,
  },
  optionTopicSelectedLable: {
    fontSize: RFValue(12),
    fontFamily: Fonts.ARIAL_ROUNDED_BOLD,
    color: Colors.SECONDARY,
  },
  optionTopicSelectedIcon: {
    width: width * 0.05,
    height: width * 0.05,
    marginRight: width * 0.015,
  },
});
